python train_path.py \
--batch_size 4096 \
--datasets CIFAR10 \
--name origin_path \
--epoch 100 \
--mult_gpu \
--randomseed 7 \
--direction_type pca \
--optimizer sgd \
--direction_type pca \
--save_direction_type weight